### ISSUE TITLE
Please migrate plugin to 4.16

### ISSUE THREAD

**Issue by Kirmas** [VSZue/DonAINavigation#6]
Could you please add Hash function for `struct FLocVector : public FVector`. You can do it in next way `FORCEINLINE friend uint32 GetTypeHash(const FLocVector& Temp) { return ::GetTypeHash(FVector(Temp.X, Temp.Y, Temp.Z)); }` 

Best regards

**Comment by VSZue** [comment]
Hey, this was already done last month, in the Master branch:
https://github.com/VSZue/DonAINavigation/blob/master/Source/DonAINavigation/Classes/DonNavigationManager.h

Which version are you checking?

**Comment by VSZue** [comment]
Also FLocVector was removed from the plugin a while ago and renamed to FDonNavigationLocVector.

Guessing you are looking at an older version of the plugin.

**Comment by Kirmas** [comment]
Never mind. I checked version from http://www.drunkonnectar.com/3d-pathfinding-ue4/ and don't checked git version. 
I`m so sorry.

**Comment by VSZue** [comment]
That's fine! No problem at all :)
